language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '10' # recent postgres version on Travis
dist: xenial # uses xenial environment
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  # - psql -c 'create database "boilermaker-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
script:
  # - npm test # test the code
  - npm run build-client # make the bundle
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: cloak-n-dogger
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: OfbIdZux/Yc8mgN1CPJB9a5K7eToeLBgJsQqbpJ76ei1Zv8Pd9qFlGkuavWlYkgNLvRQYlD/71szOQgR0nW4KMOyaCuToLhrYjCB9gSNQFsSjkiZ0VLnQx+KvE8KzjKsEcAmGEI+jPiElX1BaXK9aL4N3y9O95kcoTz55M/HsFkSmV3kuUIQ2qwkKlAGezgPrOgDmNKQir3AllRMceCEroIoUVFErtlPqcprpZeymcbOlwx+jrVg44a5eipfnhwTAVG4N8bMwPOHAH2GUnDQy2HNifs7H5e2RfITtzAVv2yOAgu+ZeFiRMAq96smoQE7gzJ9ZpWGKKS1St2XbnFX3QRDmNFYgenbzLIwoWuSErx43giVs7nbbhfQP3FiaRmicBUIEktDPr4G7eoQqlczSOGRceXDRoXA/iTy53T0V4+qeZYCWxrMBThniTvPTIfg//RHKrWwbV/IYIQnmEJIR681tAfBe33bRiOkWvpk57IZWXDC23EsRpDPnroQdicQzrpSy6MtpOCqpepjGNbcfeOtxHzSAjKGVI/9uHLZRIxdgzE1uuUPfoYLZZT5dQqKE0yLzqzIVlwo1rcopwjWLQjrqjWO3WbLHDviby7Dyby9FkloN7cA2CCj29iB0kpbkeBhGv7UKEHCf4Vp/5lmad9oZTgKSnD7nbJs1IXmulQ=
